// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnriqkyfzmyliygnpxeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZucmlxa3lmem15bGl5Z25weGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MDA4ODcsImV4cCI6MjA3MDI3Njg4N30.U_qBHS5e8fjH-ibbr4yDM6d1GbxrC6HkyEzJig36M60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});